export const GET_POST_BY_ID = 'GET_POST_BY_ID';
export const GET_COMMENTS_BY_POST_ID = 'GET_COMMENTS_BY_POST_ID';
export const SAVE_COMMENT = 'SAVE_COMMENT';
export const ADD_COMMENT_FORM_ERROR = 'ADD_COMMENT_FORM_ERROR';
export const REMOVE_COMMENT_FORM_ERROR = 'REMOVE_COMMENT_FORM_ERROR';